cloud.aws.credentials.access-key=AKIAUFQ2HURHQ7Z5BBNF
cloud.aws.credentials.secret-key=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
cloud.aws.region.static=ap-south-1
cloud.aws.stack.auto=false

aws.accessKeyId=AKIAUFQ2HURHQ7Z5BBNF
aws.secretKey=+qqZujojheE3Xl8uE3WxQ
server.port=3000

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#security.oauth2.resource-server.jwt.issuer-uri=https://dev-rlcywm56hpdgvple.us.auth0.com/
#auth0.audience=http://localhost:3000

#google
spring.security.oauth2.client.registration.google.client-id=854748282052-4tok26suak2ecrjm896btmkhi89eufh8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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